### ISSUE TITLE
How to save the plots?

### ISSUE THREAD

**Issue by Jainu-s** [erdogant/clusteval#7]
Charts are well generated but how to save them to local folder?

**Comment by erdogant** [comment]
You need to manually click save-as at every image. An argument with path location would be more convenient. I will put in on my todo list!

**Comment by erdogant** [comment]
I created a new version with the possibility to save figures.

Update with:
`pip install -U clusteval
`
The input parameter `savefig `is a dict containing properties for the figure.
All these can be used: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

The default is:
`savefig={'fname': None, format: 'png', 'dpi ': None, 'orientation': 'portrait', 'facecolor': 'auto'}
`
Example:

```
from clusteval import clusteval
X, y = make_blobs(n_samples=600, centers=[[1, 1], [-1, -1], [1, -1]], cluster_std=0.4, random_state=0)
ce = clusteval(cluster='agglomerative', evaluate='derivative')
results = ce.fit(X)

ce.plot(savefig={'fname':'clusteval_plot.png'})
ce.scatter(X, dot_size=100, savefig={'fname':'clusteval_scatter.png'})
ce.dendrogram(savefig={'fname':'clusteval_dendrogram.png'})

```
