### ISSUE TITLE
is pip not working anymore? 

### ISSUE THREAD

**Issue by LaiaBigFish** [erdogant/clusteval#9]
I get the following 
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnection
Error('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024B20CAB400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/clusteval/ 
ERROR: Could not find a version that satisfies the requirement clusteval (from versions: none) ERROR: No matching distribution found for clusteval

**Comment by erdogant** [comment]
Thanks for the message. It seems to work on my machine. Pypi also suggests that there were some downloads today.
Have you tried to update urllib3? `pip install -U urllib3`
